# Generated by Django 4.1 on 2023-01-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='trend',
            field=models.BooleanField(default=False),
        ),
    ]
